#!/bin/bash


for j in 1; do
	for i in *.cnf; do 
	
#		(time manysat2.0 $i -no-luby -rinc=1.5 -phase-saving=0 -rnd-freq=0.02 -ncores=2 -limitEx=10 -det=0 -ctrl=0 \
#			> performance/manysat/$(basename $i .cnf).try$j.sol2) &> performance/manysat/$(basename $i .cnf).try$j.time2
		
#		(time manysat2.0 $i -no-luby -rinc=1.5 -phase-saving=0 -rnd-freq=0.02 -ncores=4 -limitEx=10 -det=0 -ctrl=0 \
#			> performance/manysat/$(basename $i .cnf).try$j.sol4) &> performance/manysat/$(basename $i .cnf).try$j.time4

		(time manysat2.0 $i -no-luby -rinc=1.5 -phase-saving=0 -rnd-freq=0.02 -ncores=8 -limitEx=10 -det=0 -ctrl=0 \
			> performance/manysat/$(basename $i .cnf).try$j.sol8) &> performance/manysat/$(basename $i .cnf).try$j.time8
			
#		(time plingeling -t 2 $i > SAT-Race-2010-CNF/finalobs/$(basename $i .cnf).try$j.sol2) &> SAT-Race-2010-CNF/finalobs/$(basename $i .cnf).try$j.time2
#		(time plingeling -t 4 $i > performance/plingeling/$(basename $i .cnf).try$j.sol4) &> performance/plingeling/$(basename $i .cnf).try$j.time4
#		(time plingeling -t 8 $i > SAT-Race-2010-CNF/finalobs/$(basename $i .cnf).try$j.sol8) &> SAT-Race-2010-CNF/finalobs/$(basename $i .cnf).try$j.time8
		
		
		(time minisat $i -no-luby -rinc=1.5 -phase-saving=0 -rnd-freq=0.02 > performance/minisat/$(basename $i .cnf).try$j.sol)\
			&> performance/minisat/$(basename $i .cnf).try$j.time
	done
done

