/**************************************************************/
/* Automatically generated by './mkconfig.sh'.  Do note edit! */
/**************************************************************/
#define YALS_OS "Linux emsys1.ee.iitb.ac.in 2.6.43.8-1.fc15.i686.PAE i686"
#define YALS_COMPILED "Wed Jun 17 16:50:50 IST 2015"
#define YALS_RELEASED "Tue Apr 29 19:18:49 CEST 2014"
#define YALS_VERSION "03l"
#define YALS_ID "3742c36850f41a20c435f2eaf89205fd7e55fa03"
