#!/bin/bash

#mkdir sc14-app/manysat
#for i in sc14-app/*.cnf; do 
#	(time manysat2.0 $i -no-luby -rinc=1.5 -phase-saving=0 -rnd-freq=0.02 -ncores=4 -limitEx=10 -det=0 -ctrl=0 \
#		> sc14-app/manysat/$(basename $i .cnf).sol) &> sc14-app/manysat/$(basename $i .cnf).time
#done

#mkdir sc14-app/plingeling
#for i in sc14-app/*.cnf; do 
#	(time plingeling $i > sc14-app/plingeling/$(basename $i .cnf).sol) &> sc14-app/plingeling/$(basename $i .cnf).time
#done

for i in test.cnf; do 
	for j in 5
	do 
		time ./p1 $i -nproblems=$j 
		time ./part2solve $i 
	done
	rm gen*
done
