/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux emsys1.ee.iitb.ac.in 2.6.43.8-1.fc15.i686.PAE i686"
#define LGL_COMPILED "Wed Jun 17 16:51:01 IST 2015"
#define LGL_RELEASED "Tue Apr 29 19:18:49 CEST 2014"
#define LGL_VERSION "ayv"
#define LGL_ID "86bf266b9332599f1b876e28a02fe8427aeaa2db"
